import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from './providers';
import Sidebar from "./components/sideBar";
import { HStack } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Providers>
          <HStack spacing={5} align="flex-start">
            <Sidebar />
            <div style={{ paddingTop: "30px" }}>{children}</div>
          </HStack>
        </Providers>
      </body>
    </html>
  );
}
